language: node_js
node_js:
  - 8

install:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: russbiggs@gmail.com
  skip_cleanup: true
  api_key:
    secure: C9itciN8HwIq0BC6oQmHaRTU9PieeFWcNEFbEnU6WHSGblk2AfVnPhnkt+JhfaTsugHTjPQpNYHdWByaLHKWg6AskVjAFtqusLavm/cxKpN5IzY0AHnoSGOimPTqL1lMVbIjLb3l3ZjgHMv5yh+ibpzxmaNpe2vFM0syF2kAa8yMqgRrFPFca6+mxwiLpztbDQ1i5efaytszCdaPsGUXPqvCwQPnoPyPDxImhWypCEXH4IoU2y/3d8kXlgsEZA6Zc8lMa3KpCrmS0Qg/F4U0cpvALd26GWVe3VPsiTtEdwwf0jjKhfrGrFlTbGfRIiaLA3cc3NNid/VNidmXFqcz4yHAzxHJpHlTD8cNS5ZkhtQrePag3t7HgFndFiRI+BSAWpAOvpqAFOM09OFBhbQusfltxkzadlDk/nxao1Jv/HwqklTJvXKM02JbNtszHu88vcsGdQY6f5Xon6ramYsOil6htr8eEUEA9ruC6fD3LTkmKd4PIWNFk/G80l2JDbf9nle6kahRDVDJJNb4sjLGVDqByQi7QjWlxmQ17b6xkoJmx7hG64PSdg6AIbBn7bzEcT9DIAVyjnnO2tBgOuHBtuoV0L0MLy5u0qhedQk0DtyArGD/WGB9y+I2hf9U/0KSYH7JhHTwWVaXXT0iEWuL5BHjyKyuSABjOZyNcGbzl0U=
  on:
    tags: true
    repo: russbiggs/asturlab
